apiVersion: v2
name: disturbed-cli
description: Disturbed CLI
# renovate: datasource=docker depName=ghcr.io/hpedrorodrigues/disturbed_cli
version: 0.1.4
# renovate: datasource=docker depName=ghcr.io/hpedrorodrigues/disturbed_cli
appVersion: 1.0.36
home: https://github.com/hpedrorodrigues/disturbed_cli
sources:
  - https://github.com/hpedrorodrigues/disturbed_cli
  - https://github.com/hpedrorodrigues/helm-charts/tree/main/charts/disturbed-cli
keywords:
  - on-call
  - schedule
maintainers:
  - name: hpedrorodrigues
